config/routes.rb
Rails.application.routes.draw do
  # get 'topics/index'
  # get 'topics/show'
  # get 'topics/new'
  # get 'topics/create'
  # get 'topics/edit'
  # get 'topics/update'
  # get 'topics/destroy'
  # get 'departments/index'
  # get 'departments/show'
  # get 'departments/new'
  # get 'departments/create'
  # get 'departments/edit'
  # get 'departments/update'
  # get 'departments/destroy'
  root "departments#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :departments do
    resources :topics 
end

resources :topics do
  resources :comments, only: [:new, :create] 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/topic.rb
class Topic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  def index
        # url = /departments  (GET)
    @departments = Department.all
  end

  def show
        # url = /departments/:id  (GET)
  end

  def new
        # url = /departments/new  (GET)
    @department = Department.new
    # render partial: "form"
  end

  def create
        # url - /departments  (POST)
    @department = Department.new(department_params)

    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def edit

  @department = Department.find(params[:id])
    #  render partial: "form"
  end

  def update
        # url - /departments/:id  (PUT)
    if @department.update(department_params)
      redirect_to department_path(@department)
    else
      render :edit
    end
  end

  def destroy
        # url - "/departments/:id"  (DELETE)
    @department.destroy    
    redirect_to departments_path
  end

  private
  
    def department_params
      params.require(:department).permit(:name)
    end

  def set_department
    @department = Department.find(params[:id])
  end

end

app/controllers/items_controller.rb
class itemsController < ApplicationController
  before_action :set_departments
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
        # url - /departmentss/:departments_id/items  (GET)    
    @items = @departments.items
  end

  def show
        # url - /departmentss/:departments_id/items/:id  (GET)    
  end

  def new
        # url - /departmentss/:departments_id/items/new  (GET)
    @item = @departments.items.new
    render partial: "form"
  end

  def create
        # url - /departmentss/:departments_id/items  (POST)
    @item = @departments.items.new(item_params)

    if @item.save
      redirect_to departments_items_path(@departments)
    else
      render :new
    end
  end

  def edit
        # url - /departmentss/:departments_id/items/:id/edit  (GET)
    render partial: "form"
  end

  def update
        # url - /departmentss/:departments_id/items/:id  (PUT)    
    if @item.update(item_params)
      redirect_to departments_item_path(@departments, @item)
    else
      render :edit
    end
  end

  def destroy
        # url - /departmentss/:departments_id/items/:id  (DELETE) 
    @item.destroy
    redirect_to departments_items_path(@departments)
  end

  private
    def set_departments
      @departments = departments.find(params[:departments_id])
    end

    def set_item
      @item = item.find(params[:id])
    end

    def item_params
      params.require(:item).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/departments/__form.html.erb
<h1><%= @department.id ? 'Edit department' : 'Create department' %></h1>
<hr />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/departments/edit.html.erb
<h1>Place#edit<h1>
<p>Find me in app/views/department/edit.html.erb</p>

app/views/departments/index.html.erb
<h1>Click a Department To View Content</h1>

<%= link_to 'Create a new department', new_department_path %>

<ul>
<% @departments.each do |department| %>
  <li>  
  <%= department.name %>
  <%= link_to 'Create a new department', new_department_path %>
  <%= link_to "Delete", department, method: :delete %>
  <%= link_to "edit", department_path(department) %>
  <% end %>
</ul>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= form_for @department do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>

  <% end %>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<hr />
<p>Edit the the information below do?</p>
<br />
<%= link_to 'Edit department', edit_department_path(@department) %>
<br />
<%= link_to 'Delete department', @department, method: :delete %>

app/views/items/__form.html.erb
<h1><%= @department.id ? 'Edit Topic' : 'Create department' %></h1>
<hr />
<%= form_for [@department, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1><%= @items.id ? 'Edit Topic' : 'Create Topic' %></h1>
<hr />
<%= form_for [@department, @items] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :body %>
  <%= f.text_area :body, required: true %>
  <%= f.submit %>
<% end %>

app/views/items/new.html.erb
<h1>items #new</h1>
<p>Find me in app/views/documents/new.html.erb</p>

app/views/items/show.html.erb
<h1><%= @document.name %> - <%= @document.name %></h1>
<p><%= @document.body %></p>
<%= link_to 




# <h1><%= @department.name %> - <%= @item.name %></h1>
# <p><%= @item.body %></p>
# <h2>Comments</h2>

# <% @item.comments.each do |comment| %>
#   <%= render 'comments/comment', { comment: comment } %>
# <% end %>

# <hr />
# <%= link_to 'Add Comment', new_topic_comment_path(@titem) %>
# <%= link_to 'Edit Topic', edit_department_item_path([@department, @item]) %>
# <%= link_to 'Delete Topic', [@department, @item], method: :delete %>
# <%= link_to 'Back To Topics', department_items_path(@deparment) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDepartmentStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>